"use client";

import React from "react";
import Image from "next/image";

type SheetData = Record<string, string | boolean | undefined>;

function Field({ label, name, data, set, className = "" }: { label: string; name: string; data: SheetData; set: (name: string, value: string) => void; className?: string }) {
  return <label className={`block border border-black p-1.5 font-bold ${className}`}>{label}<input aria-label={label} value={String(data[name] || "")} onChange={(e) => set(name, e.target.value)} className="mt-1 block w-full border-b border-black bg-transparent px-0.5 text-[11px] font-normal outline-none" /></label>;
}

function Band({ children, tone = "gray" }: { children: React.ReactNode; tone?: "gray" | "blue" }) {
  return <div className={`border border-black px-2 py-1 text-center text-[13px] font-bold ${tone === "blue" ? "bg-[#dbeaf8]" : "bg-[#d9d9d9]"}`}>{children}</div>;
}

function Toggle({ label, name, data, set }: { label: string; name: string; data: SheetData; set: (name: string, value: boolean) => void }) {
  return <label className="mr-3 inline-flex items-center gap-1 text-[10px]"><input type="checkbox" checked={Boolean(data[name])} onChange={(e) => set(name, e.target.checked)} />{label}</label>;
}

export function PrimeRfbSheet({ data, onChange }: { data: SheetData; onChange: (data: SheetData) => void }) {
  const set = (name: string, value: string | boolean) => onChange({ ...data, [name]: value });
  return <div id="rfp-printable-sheet" className="mx-auto w-full max-w-[794px] min-h-[1123px] bg-white p-7 text-black shadow-md print:p-0 print:shadow-none" style={{ fontFamily: "Arial, Helvetica, sans-serif" }}>
    <Band>REQUEST FOR BILLING INVOICE (RFB Form) - LEASING SERVICES</Band>
    <div className="border-x border-b border-black text-center text-[11px] font-semibold">Kindly print this in a Letter Size Bond Paper, pens 1<br /><i>Please make sure all details provided are 100% accurate and correct to ensure fast collection of payments</i></div>
    <div className="mt-2 grid grid-cols-2"><Field label="LESSOR's registered name:" name="lessorName" data={data} set={set} /><Field label="Subject Project/Property name:" name="propertyName" data={data} set={set} /><Field label="LESSOR's billing address:" name="billingAddress" data={data} set={set} className="col-span-2" /></div>
    <div className="border border-black p-2 text-[11px] font-bold">LISTING: <Toggle label="OPEN" name="open" data={data} set={set} /><Toggle label="NON-EX" name="nonEx" data={data} set={set} /><Toggle label="NON-EX WITH TARP" name="tarp" data={data} set={set} /><Toggle label="EXCLUSIVE" name="exclusive" data={data} set={set} /><Toggle label="SOLE" name="sole" data={data} set={set} /></div>
    <div className="grid grid-cols-4"><Field label="Lessor's contact person/s for billing purposes" name="contactPerson" data={data} set={set} /><Field label="Position" name="position" data={data} set={set} /><Field label="Contact Number" name="contactNumber" data={data} set={set} /><Field label="Email Address" name="email" data={data} set={set} /></div>
    <div className="grid grid-cols-2"><Field label="LESSEE's registered name:" name="lesseeName" data={data} set={set} /><Field label="PF scheme:" name="pfScheme" data={data} set={set} /><Field label="What document are you requesting for?" name="requestedDocument" data={data} set={set} /><Field label="Lease term or Duration:" name="leaseTerm" data={data} set={set} /></div>
    <Band>COMPUTATION BREAKDOWN OF PROFESSIONAL FEE:</Band>
    <p className="border-x border-b border-black px-3 py-1 text-center text-[10px]">All payments shown below must be <u>exclusive of VAT</u>. Double-check all details before submitting.</p>
    <div className="grid grid-cols-2"><Field label="Gross / Net Leasable Area covered:" name="leaseArea" data={data} set={set} /><Field label="Monthly Basic Rental Rate:" name="monthlyRental" data={data} set={set} /><Field label="Basic Rental Rate per sqm.:" name="basicRate" data={data} set={set} /><Field label="Monthly CUSA fee:" name="cusaFee" data={data} set={set} /><Field label="No. of parking / Rental rate:" name="parking" data={data} set={set} /><Field label="No. of signages / Rental rate:" name="signages" data={data} set={set} /></div>
    <div className="border border-black bg-[#95d247] p-4 text-center text-[17px] font-bold">TOTAL AMOUNT DUE (PROFESSIONAL FEE): <input aria-label="Total amount due" value={String(data.totalAmount || "")} onChange={(e) => set("totalAmount", e.target.value)} className="ml-2 w-36 border-b border-black bg-transparent text-center outline-none" /> Php</div>
    <div className="grid grid-cols-2"><Field label="Date Contract Signed:" name="contractDate" data={data} set={set} /><Field label="Date of Advance Payment:" name="advancePaymentDate" data={data} set={set} /></div>
    <Band>PLEASE REFER TO PAGE 2 FOR CREDIT SHARING FORM FOR THIS ACCOUNT</Band>
    <div className="mt-8 grid grid-cols-3"><Field label="Prepared by:" name="preparedBy" data={data} set={set} /><Field label="Reviewed by: (Team Leader)" name="reviewedBy" data={data} set={set} /><Field label="Date approved" name="dateApproved" data={data} set={set} /></div>
    <p className="mt-2 border border-black p-2 text-center text-[10px] text-red-800">Please submit this to the Accounting Team together with the accomplished Credit Sharing Form, signed Contract of Lease, and other necessary documents.</p>
  </div>;
}

export function PrimeCreditSharingSheet({ data, onChange }: { data: SheetData; onChange: (data: SheetData) => void }) {
  const set = (name: string, value: string | boolean) => onChange({ ...data, [name]: value });
  const rows = Array.from({ length: 8 }, (_, index) => index);
  return <div id="rfp-printable-sheet" className="mx-auto w-full max-w-[794px] min-h-[1123px] bg-white p-7 text-black shadow-md print:p-0 print:shadow-none" style={{ fontFamily: "Arial, Helvetica, sans-serif" }}>
    <div className="flex items-center gap-4 border-b-2 border-[#dbeaf8] pb-2"><Image src="/prime-blue-logo.png" alt="PRIME Philippines" width={180} height={60} unoptimized className="h-12 w-auto" /><div className="flex-1 bg-[#dbeaf8] py-2 text-center text-[20px] font-bold">PRIME CREDIT SHARING FORM<br /><span className="text-[13px]">PROPERTY INTERACTIVE MARKETING ENTERPRISE REALTY CORPORATION</span></div></div>
    <p className="my-2 text-[11px] italic">Please make sure all details provided are 100% accurate and correct to ensure fast collection of payments.</p>
    <div className="grid grid-cols-2"><Field label="Lessor's Registered Name" name="lessorName" data={data} set={set} /><Field label="Subject Project / Property Name" name="propertyName" data={data} set={set} /><Field label="Lessee's Registered Name" name="lesseeName" data={data} set={set} /><Field label="PF Scheme / PF Amount" name="pfDetails" data={data} set={set} /></div>
    <Band tone="blue">CREDIT SHARING BREAKDOWN</Band><p className="border-x border-b border-black p-2 text-[10px] italic font-semibold">All percentages detailed below will be considered final. If not applicable, kindly write “N/A”.</p>
    <div className="grid grid-cols-2"><Field label="Internal Credit Share %" name="internalShare" data={data} set={set} /><Field label="External Credit Share %" name="externalShare" data={data} set={set} /><Field label="PRIME's Net Commission Receivable" name="netCommission" data={data} set={set} className="col-span-2" /></div>
    <Band tone="blue">CO-BROKER INFORMATION</Band><div className="border-x border-b border-black p-2"><Toggle label="Signed Broker's Client Registration Form" name="brokerRegistration" data={data} set={set} /><Toggle label="Copy of Valid ID with Specimen Signature" name="validId" data={data} set={set} /><Toggle label="Memorandum of Agreement" name="moa" data={data} set={set} /></div>
    <div className="grid grid-cols-2"><Field label="Broker's or Agent's Name" name="brokerName" data={data} set={set} /><Field label="PRC License ID Number" name="prc" data={data} set={set} /><Field label="Agreed Commission Amount" name="commission" data={data} set={set} /><Field label="Contact Number" name="contactNumber" data={data} set={set} /><Field label="Email Address" name="email" data={data} set={set} /><Field label="Remarks" name="remarks" data={data} set={set} /></div>
    <Band tone="blue">CREDIT SHARING WITHIN PRIME PHILIPPINES</Band><p className="border-x border-b border-black p-1 text-[10px] italic">Credit sharing percentages below are based on the Internal Credit Share only.</p>
    <table className="w-full border-collapse text-[10px]"><thead><tr className="bg-[#eeeeee]"><th className="border border-black p-1">Name</th><th className="border border-black p-1">Department</th><th className="border border-black p-1">Credit Share</th><th className="border border-black p-1">Acknowledgement, Signature</th></tr></thead><tbody>{rows.map((row) => <tr key={row}>{["name", "department", "share", "signature"].map((field) => <td key={field} className="border border-black p-0.5"><input aria-label={`Credit ${field} ${row + 1}`} value={String(data[`credit_${field}_${row}`] || "")} onChange={(e) => set(`credit_${field}_${row}`, e.target.value)} className="w-full bg-transparent outline-none" /></td>)}</tr>)}</tbody></table>
    <Band tone="blue">THE FOLLOWING PORTIONS ARE TO BE PROCESSED BY THE ACCOUNTING AND FINANCE TEAM</Band><div className="grid grid-cols-2"><Field label="Received By / Date Received" name="receivedBy" data={data} set={set} /><Field label="Validated By / Date Validated" name="validatedBy" data={data} set={set} /><Field label="Remarks" name="financeRemarks" data={data} set={set} className="col-span-2" /></div>
  </div>;
}

function GreatWorkHeader({ title }: { title: string }) {
  return <div className="flex items-center gap-4 border-b border-black pb-1"><Image src="/greatwork-logo.png" alt="GreatWork" width={155} height={44} unoptimized className="h-10 w-auto object-contain" /><div className="flex-1 bg-[#faebeb] py-2 text-center leading-tight"><div className="text-[19px] font-bold text-[#ae2731]">{title}</div><div className="text-[12px] font-bold">MY GREATWORK SPACES INC.</div></div></div>;
}

function GreatWorkBand({ children }: { children: React.ReactNode }) {
  return <div className="border border-black bg-[#faebeb] px-2 py-1 text-[13px] font-bold text-[#ae2731]">{children}</div>;
}

export function GreatWorkRfbSheet({ data, onChange }: { data: SheetData; onChange: (data: SheetData) => void }) {
  const set = (name: string, value: string | boolean) => onChange({ ...data, [name]: value });
  return <div id="rfp-printable-sheet" className="mx-auto min-h-[1123px] w-full max-w-[794px] bg-white p-7 text-black shadow-md print:p-0 print:shadow-none" style={{ fontFamily: "Arial, Helvetica, sans-serif" }}>
    <GreatWorkHeader title="REQUEST FOR BILLING (RFB)" />
    <div className="mt-3"><GreatWorkBand>TIMING OF SUBMISSION</GreatWorkBand><div className="grid grid-cols-2"><Field label="Date Accomplished (MM/DD/YY):" name="gw_rfb_accomplishedDate" data={data} set={set} /><Field label="Billing Due Date (MM/DD/YY):" name="gw_rfb_dueDate" data={data} set={set} /></div></div>
    <div className="mt-3"><GreatWorkBand>LESSEE DETAILS</GreatWorkBand><div className="grid grid-cols-2"><Field label="Client's Registered Name:" name="gw_rfb_clientName" data={data} set={set} /><Field label="Lease Term:" name="gw_rfb_leaseTerm" data={data} set={set} /><Field label="Registered Address:" name="gw_rfb_address" data={data} set={set} /><div className="border border-black p-1.5 text-[11px] font-bold">Lease type:<br /><Toggle label="New Client" name="gw_rfb_newClient" data={data} set={set} /><Toggle label="Contract Renewal" name="gw_rfb_renewal" data={data} set={set} /></div></div><div className="grid grid-cols-2"><div className="border border-black p-1.5 text-[11px]"><b>KYC Documents Completed:</b> <Toggle label="Yes" name="gw_rfb_kycYes" data={data} set={set} /><Toggle label="No" name="gw_rfb_kycNo" data={data} set={set} /><p className="mt-1 font-bold">Service Type:</p><div className="grid grid-cols-2"><Toggle label="Virtual Office" name="gw_rfb_virtualOffice" data={data} set={set} /><Toggle label="Dedicated Desk" name="gw_rfb_dedicatedDesk" data={data} set={set} /><Toggle label="Service Office" name="gw_rfb_serviceOffice" data={data} set={set} /><Toggle label="Enterprise" name="gw_rfb_enterprise" data={data} set={set} /><Toggle label="Co-Working" name="gw_rfb_coworking" data={data} set={set} /><Toggle label="Events" name="gw_rfb_events" data={data} set={set} /><Toggle label="Others" name="gw_rfb_otherService" data={data} set={set} /></div></div><div className="border border-black p-1.5 text-[11px]"><Field label="TIN:" name="gw_rfb_tin" data={data} set={set} className="border-0 p-0" /><b>Branch:</b><br /><Toggle label="GW2" name="gw_rfb_gw2" data={data} set={set} /><Toggle label="GW3" name="gw_rfb_gw3" data={data} set={set} /><Toggle label="GW4" name="gw_rfb_gw4" data={data} set={set} /></div></div><Field label="Remarks:" name="gw_rfb_lesseeRemarks" data={data} set={set} /></div>
    <div className="mt-3"><GreatWorkBand>BILLING CONTACT PERSON DETAILS</GreatWorkBand><div className="grid grid-cols-2"><Field label="Name:" name="gw_rfb_contactName" data={data} set={set} /><Field label="Designation:" name="gw_rfb_designation" data={data} set={set} /><Field label="Contact Number:" name="gw_rfb_contactNumber" data={data} set={set} /><Field label="Email Address:" name="gw_rfb_email" data={data} set={set} /></div></div>
    <div className="mt-3"><GreatWorkBand>BILLING BREAKDOWN</GreatWorkBand><p className="border-x border-b border-black p-1 text-[10px] italic">All details provided will be the basis of billing to the client. Amounts must be exclusive of VAT.</p><div className="grid grid-cols-2"><Field label="Monthly Basic Rental Rate:" name="gw_rfb_monthlyRental" data={data} set={set} /><Field label="Monthly Parking Rental:" name="gw_rfb_parkingRental" data={data} set={set} /><Field label="Initial / Advance Fee — Description / No. of Months / Amount:" name="gw_rfb_advanceFee" data={data} set={set} /><Field label="Security Deposit — Description / No. of Months / Amount:" name="gw_rfb_securityDeposit" data={data} set={set} /><Field label="Others — Description / No. of Months / Amount:" name="gw_rfb_others" data={data} set={set} className="col-span-2" /><Field label="Total Contract Value:" name="gw_rfb_contractValue" data={data} set={set} /><Field label="Total Amount Due for Billing:" name="gw_rfb_amountDue" data={data} set={set} /><Field label="Date Contract Signed (MM/DD/YY):" name="gw_rfb_contractDate" data={data} set={set} className="col-span-2" /></div></div>
    <div className="mt-3"><GreatWorkBand>REQUESTOR DETAILS — NOTE: RFB MUST BE APPROVED BY TL</GreatWorkBand><div className="grid grid-cols-2"><Field label="Requested By:" name="gw_rfb_requestedBy" data={data} set={set} /><Field label="Approved By:" name="gw_rfb_approvedBy" data={data} set={set} /><Field label="Designation:" name="gw_rfb_requestorDesignation" data={data} set={set} /><Field label="Designation:" name="gw_rfb_approverDesignation" data={data} set={set} /><Field label="Signature:" name="gw_rfb_requestorSignature" data={data} set={set} /><Field label="Signature:" name="gw_rfb_approverSignature" data={data} set={set} /><Field label="Date (DD/MM/YY):" name="gw_rfb_requestDate" data={data} set={set} /><Field label="Date (DD/MM/YY):" name="gw_rfb_approvalDate" data={data} set={set} /></div><p className="border border-black p-1 text-center text-[10px] italic text-[#ae2731]">The above signatures are not the basis for commission. Please refer to the Credit Sharing Form for this account.</p></div>
    <div className="mt-3"><GreatWorkBand>TO BE FILLED OUT BY FINANCE / ACCOUNTING ONLY</GreatWorkBand><div className="grid grid-cols-2"><Field label="Reviewed By:" name="gw_rfb_reviewedBy" data={data} set={set} /><Field label="Validated By:" name="gw_rfb_validatedBy" data={data} set={set} /><Field label="Date Reviewed (MM/DD/YY):" name="gw_rfb_reviewDate" data={data} set={set} /><Field label="Date Validated (MM/DD/YY):" name="gw_rfb_validationDate" data={data} set={set} /><Field label="Remarks:" name="gw_rfb_financeRemarks" data={data} set={set} className="col-span-2" /></div></div>
  </div>;
}

export function GreatWorkCreditSharingSheet({ data, onChange }: { data: SheetData; onChange: (data: SheetData) => void }) {
  const set = (name: string, value: string | boolean) => onChange({ ...data, [name]: value });
  const rows = Array.from({ length: 8 }, (_, index) => index);
  return <div id="rfp-printable-sheet" className="mx-auto min-h-[1123px] w-full max-w-[794px] bg-white p-7 text-black shadow-md print:p-0 print:shadow-none" style={{ fontFamily: "Arial, Helvetica, sans-serif" }}>
    <GreatWorkHeader title="GREATWORK CREDIT SHARING FORM" />
    <p className="my-2 text-[11px] italic">Please make sure all details provided are 100% accurate and correct to ensure fast collection of payments.</p>
    <div className="grid grid-cols-2"><Field label="Client's Registered Name" name="gw_csf_clientName" data={data} set={set} /><Field label="Lease Period" name="gw_csf_leasePeriod" data={data} set={set} /></div>
    <GreatWorkBand>CREDIT SHARING BREAKDOWN</GreatWorkBand><p className="border-x border-b border-black p-1 text-[10px] italic font-semibold">All details below shall be the basis of Finance for commission computations. Make sure to double-check all details.</p><div className="grid grid-cols-2"><Field label="Internal Credit Share %" name="gw_csf_internalShare" data={data} set={set} /><Field label="External Credit Share %" name="gw_csf_externalShare" data={data} set={set} /></div>
    <GreatWorkBand>CO-BROKER INFORMATION/ REFERRAL INFORMATION</GreatWorkBand><div className="border-x border-b border-black p-2 text-[10px] italic">Please write “N/A” if there is no Co-broker.<br /><span className="not-italic"><Toggle label="Signed Broker's Client Registration Form" name="gw_csf_registration" data={data} set={set} /><Toggle label="Copy of Valid ID with Specimen Signature" name="gw_csf_validId" data={data} set={set} /><Toggle label="Memorandum of Agreement" name="gw_csf_moa" data={data} set={set} /></span></div><div className="grid grid-cols-2"><Field label="Broker's or Agent's Name" name="gw_csf_brokerName" data={data} set={set} /><Field label="PRC License ID Number" name="gw_csf_prc" data={data} set={set} /><Field label="Agreed Commission Amount for Broker/Agent" name="gw_csf_commission" data={data} set={set} /><Field label="Contact Number" name="gw_csf_contactNumber" data={data} set={set} /><Field label="Email Address" name="gw_csf_email" data={data} set={set} /><Field label="Remarks" name="gw_csf_brokerRemarks" data={data} set={set} /></div>
    <GreatWorkBand>CREDIT SHARING WITHIN GREATWORK</GreatWorkBand><p className="border-x border-b border-black p-1 text-[10px] italic">Credit sharing percentages below are based on the Internal Credit Share only. If a field is not applicable, kindly write “N/A”.</p><table className="w-full border-collapse text-[10px]"><thead><tr className="bg-[#eeeeee]"><th className="border border-black p-1">Name</th><th className="border border-black p-1">Department</th><th className="border border-black p-1">Credit Share</th><th className="border border-black p-1">Acknowledgement, Signature</th></tr></thead><tbody>{rows.map((row) => <tr key={row}>{["name", "department", "share", "signature"].map((field) => <td key={field} className="border border-black p-0.5"><input aria-label={`GreatWork credit ${field} ${row + 1}`} value={String(data[`gw_csf_credit_${field}_${row}`] || "")} onChange={(e) => set(`gw_csf_credit_${field}_${row}`, e.target.value)} className="w-full bg-transparent outline-none" /></td>)}</tr>)}</tbody></table>
    <div className="mt-3"><GreatWorkBand>THE FOLLOWING PORTIONS ARE TO BE PROCESSED BY THE ACCOUNTING AND FINANCE TEAM</GreatWorkBand><div className="grid grid-cols-2"><Field label="Received By" name="gw_csf_receivedBy" data={data} set={set} /><Field label="Validated By" name="gw_csf_validatedBy" data={data} set={set} /><Field label="Date Received (DD/MM/YY)" name="gw_csf_receivedDate" data={data} set={set} /><Field label="Date Validated (DD/MM/YY)" name="gw_csf_validatedDate" data={data} set={set} /><Field label="Remarks" name="gw_csf_receivedRemarks" data={data} set={set} /><Field label="Remarks" name="gw_csf_validatedRemarks" data={data} set={set} /></div></div>
  </div>;
}
