"use client";

import React from "react";
import { AutoResizeTextarea } from "./AutoResizeTextarea";
import { PrimeDatePicker } from "./PrimeDatePicker";

type TravelData = Record<string, any>;

export function TravelBudgetSheet({ data, onChange }: { data: TravelData; onChange: (data: TravelData) => void }) {
  const set = (key: string, value: any) => onChange({ ...data, [key]: value });
  const expenses = ["Airfare", "Hotel Accommodation", "Meals & Per Diem", "Ground Transportation", "Fuel / Toll / Parking (if applicable)", "Registration / Seminar Fee", "Representation Expense (If approved)", "Communication Expense (If applicable)", "Miscellaneous"];
  const input = (key: string, className = "") => <input aria-label={key} value={data[key] ?? ""} onChange={(e) => set(key, e.target.value)} className={`w-full bg-transparent px-1 py-0.5 outline-none ${className}`} />;
  const checkbox = (key: string, label: string) => <label className="inline-flex items-center gap-1 mr-3"><input type="checkbox" checked={Boolean(data[key])} onChange={(e) => set(key, e.target.checked)} />{label}</label>;
  return <div id="rfp-printable-sheet" className="travel-budget-sheet mx-auto w-full max-w-[850px] bg-white p-7 text-[10px] text-black shadow-md print:p-0 print:shadow-none" style={{ fontFamily: '"Times New Roman", Times, serif' }}>
    <div className="border-t border-gray-300 pt-1 text-center"><h1 className="text-lg font-bold">TRAVEL BUDGET REQUEST FORM</h1><p className="text-[9px] italic">To be completed by the employee and routed for approval prior to booking.</p></div>
    <TravelSection title="1. EMPLOYEE INFORMATION"><div className="grid grid-cols-4 border border-gray-400">{[["Employee Name","employeeName"],["Department","department"],["Position / Title","positionTitle"],["Immediate Supervisor","immediateSupervisor"],["Cost Center / GL Code","costCenter"],["Date of Request","requestDate"]].map(([label,key]) => <React.Fragment key={key}><label className="border-b border-r border-gray-400 p-1">{label}</label><div className="border-b border-gray-400 p-0.5">{key === "requestDate" ? <PrimeDatePicker value={data[key] ?? ""} onChange={(v) => set(key, v)} className="min-w-0" /> : input(key)}</div></React.Fragment>)}</div></TravelSection>
    <TravelSection title="2. TRAVEL DETAILS"><div className="grid grid-cols-4 border border-gray-400">{[["Destination","destination"],["Project / Event Name","projectName"],["Purpose of Travel","purposeTravel"],["Departure Date","departureDate"],["Return Date","returnDate"],["No. of Travel Days","travelDays"],["No. of Travelers","travelers"]].map(([label,key], i) => <React.Fragment key={key}><label className="border-b border-r border-gray-400 p-1">{label}</label><div className="border-b border-gray-400 p-0.5">{key.includes("Date") ? <PrimeDatePicker value={data[key] ?? ""} onChange={(v) => set(key, v)} className="min-w-0" /> : input(key)}</div></React.Fragment>)}<div className="col-span-2 border-b border-r border-gray-400 p-1">Mode of Travel: {checkbox("air","Air")}{checkbox("land","Land")}{checkbox("sea","Sea")}</div><div className="col-span-2 border-b border-gray-400 p-1">Accommodation Required: {checkbox("accommodationYes","Yes")}{checkbox("accommodationNo","No")}</div><div className="col-span-2 border-r border-gray-400 p-1">Trip Type: {checkbox("domestic","Domestic")}{checkbox("international","International")}</div><div className="col-span-2 p-1">Funding: {checkbox("advance","Advance")}{checkbox("reimbursement","Reimbursement")}</div></div></TravelSection>
    <TravelSection title="3. BUSINESS JUSTIFICATION"><AutoResizeTextarea value={data.businessJustification ?? ""} onChange={(e) => set("businessJustification", e.target.value)} rows={2} placeholder="Business purpose, expected deliverables, and benefit to the company." className="w-full border border-gray-400 p-2 italic" /></TravelSection>
    <TravelSection title="4. ESTIMATED TRAVEL BUDGET"><table className="w-full border-collapse border border-gray-400"><thead><tr className="bg-gray-100"><th className="border border-gray-400 p-1 text-left">Expense Category</th><th className="border border-gray-400 p-1">Estimated</th><th className="border border-gray-400 p-1">Approved</th><th className="border border-gray-400 p-1">Actual</th></tr></thead><tbody>{expenses.map((name) => <tr key={name}><td className="border border-gray-400 p-1">{name}</td>{["estimated","approved","actual"].map((field) => <td key={field} className="border border-gray-400 p-0.5">{input(`${field}_${name}`, "text-right")}</td>)}</tr>)}<tr><td className="border border-gray-400 p-1 font-bold">Total</td>{["estimated","approved","actual"].map((field) => <td key={field} className="border border-gray-400 p-0.5">{input(`total_${field}`, "text-right")}</td>)}</tr></tbody></table><p className="text-[9px] italic text-gray-500">Amounts should not exceed applicable per-diem / travel policy limits.</p></TravelSection>
    <TravelSection title="5. SUPPORTING DOCUMENTS"><div className="grid grid-cols-2 border border-gray-400 p-1">{[["travelItinerary","Travel Itinerary"],["flightQuotation","Flight Quotation"],["hotelQuotation","Hotel Quotation"],["meetingInvitation","Meeting / Event Invitation"],["budgetEstimate","Budget Estimate"],["otherDocument","Other (specify)" ]].map(([key,label]) => <div key={key}>{checkbox(key, label)}</div>)}</div></TravelSection>
    <TravelSection title="6. APPROVAL WORKFLOW"><table className="w-full border-collapse border border-gray-400"><thead><tr className="bg-gray-100"><th className="border border-gray-400 p-1 text-left">Approval Level</th><th className="border border-gray-400 p-1 text-left">Name</th><th className="border border-gray-400 p-1 text-left">Signature</th><th className="border border-gray-400 p-1 text-left">Date</th></tr></thead><tbody>{["Requested by","Immediate Supervisor","Finance Approver"].map((label) => <tr key={label}><td className="border border-gray-400 p-1">{label}</td>{["name","signature","date"].map((field) => <td key={field} className="border border-gray-400 p-0.5">{field === "date" ? <PrimeDatePicker value={data[`${label}_${field}`] ?? ""} onChange={(v) => set(`${label}_${field}`, v)} ariaLabel={`${label} approval`} className="min-w-0" /> : input(`${label}_${field}`)}</td>)}</tr>)}</tbody></table><p className="mt-1 text-[9px] italic text-gray-500">Submit 7–10 business days before departure with all approvals and supporting documents attached.</p><p className="mt-5 text-[9px] italic text-gray-500">Retain a copy for your records.</p></TravelSection>
  </div>;
}

function TravelSection({ title, children }: { title: string; children: React.ReactNode }) { return <section className="mb-2"><h2 className="border-b-2 border-gray-700 pb-0.5 text-[12px] font-bold">{title}</h2><div className="mt-1">{children}</div></section>; }
