-- Forms Portal database schema.
-- Hyphens require quoted PostgreSQL identifiers; these names intentionally
-- follow the requested forms-portal-(table-name) convention.

create table if not exists "forms-portal-form_destinations" (
  id bigint generated by default as identity primary key,
  form_type varchar(32) not null unique,
  display_name varchar(120) not null,
  clickup_workspace_id varchar(64) not null default '',
  clickup_list_id varchar(64) not null default '',
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint forms_portal_form_destinations_type_check
    check (form_type in ('rfp', 'gw-rfp', 'travel-budget', 'po', 'pcv'))
);

create index if not exists forms_portal_form_destinations_enabled_idx
  on "forms-portal-form_destinations" (enabled);

insert into "forms-portal-form_destinations"
  (form_type, display_name, clickup_workspace_id, clickup_list_id, enabled)
values
  ('rfp', 'PRIME RFP submissions', '9014981136', '901420772915', true),
  ('gw-rfp', 'GW RFP submissions', '9014981136', '901420772915', true),
  ('travel-budget', 'Travel Budget requests', '9014981136', '901420772915', true),
  ('po', 'Purchase Order requests', '9014981136', '', true),
  ('pcv', 'Petty Cash Voucher requests', '9014981136', '', true)
on conflict (form_type) do update set
  display_name = excluded.display_name,
  clickup_workspace_id = excluded.clickup_workspace_id,
  clickup_list_id = excluded.clickup_list_id,
  enabled = excluded.enabled,
  updated_at = now();

create table if not exists "forms-portal-RBAC" (
  id bigint generated by default as identity primary key,
  user_id varchar(120) not null unique,
  name varchar(160) not null,
  email varchar(255) not null unique,
  department varchar(160) not null default 'Operations',
  role varchar(32) not null,
  status varchar(16) not null default 'active',
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  constraint forms_portal_rbac_role_check
    check (role in ('admin', 'approver', 'finance', 'requestor')),
  constraint forms_portal_rbac_status_check
    check (status in ('active', 'inactive'))
);

create index if not exists forms_portal_rbac_department_idx
  on "forms-portal-RBAC" (department);

create index if not exists forms_portal_rbac_status_idx
  on "forms-portal-RBAC" (status);

insert into "forms-portal-RBAC"
  (user_id, name, email, department, role, status)
values
  ('usr-1', 'Dave Policarpio', 'dave@primephilippines.com', 'Executive', 'admin', 'active'),
  ('usr-2', 'Finance Officer', 'finance@primephilippines.com', 'Finance & Accounting', 'finance', 'active'),
  ('usr-3', 'Department Team Leader', 'tl.lead@primephilippines.com', 'ISD', 'approver', 'active'),
  ('usr-4', 'Operations Staff', 'staff@primephilippines.com', 'Operations', 'requestor', 'active')
on conflict (user_id) do update set
  name = excluded.name,
  email = excluded.email,
  department = excluded.department,
  role = excluded.role,
  status = excluded.status,
  updated_at = now();
