-- Forms Portal database schema.
-- Hyphens require quoted PostgreSQL identifiers; these names intentionally
-- follow the requested forms-portal-(table-name) convention.

create table if not exists "forms-portal-form_destinations" (
  id bigint generated by default as identity primary key,
  form_type varchar(32) not null unique,
  display_name varchar(120) not null,
  clickup_workspace_id varchar(64) not null default '',
  clickup_list_id varchar(64) not null default '',
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint forms_portal_form_destinations_type_check
    check (form_type in ('rfp', 'gw-rfp', 'travel-budget', 'po', 'pcv'))
);

create index if not exists forms_portal_form_destinations_enabled_idx
  on "forms-portal-form_destinations" (enabled);

insert into "forms-portal-form_destinations"
  (form_type, display_name, clickup_workspace_id, clickup_list_id, enabled)
values
  ('rfp', 'PRIME RFP submissions', '9014981136', '901420772915', true),
  ('gw-rfp', 'GW RFP submissions', '9014981136', '901420772915', true),
  ('travel-budget', 'Travel Budget requests', '9014981136', '901420772915', true),
  ('po', 'Purchase Order requests', '9014981136', '', true),
  ('pcv', 'Petty Cash Voucher requests', '9014981136', '', true)
on conflict (form_type) do update set
  display_name = excluded.display_name,
  clickup_workspace_id = excluded.clickup_workspace_id,
  clickup_list_id = excluded.clickup_list_id,
  enabled = excluded.enabled,
  updated_at = now();

create table if not exists "forms-portal-RBAC" (
  id bigint generated by default as identity primary key,
  user_id varchar(120) not null unique,
  name varchar(160) not null,
  email varchar(255) not null unique,
  department varchar(160) not null default 'Operations',
  role varchar(32) not null,
  status varchar(16) not null default 'active',
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  constraint forms_portal_rbac_role_check
    check (role in ('admin', 'approver', 'finance', 'requestor')),
  constraint forms_portal_rbac_status_check
    check (status in ('active', 'inactive'))
);

create index if not exists forms_portal_rbac_department_idx
  on "forms-portal-RBAC" (department);

create index if not exists forms_portal_rbac_status_idx
  on "forms-portal-RBAC" (status);

create table if not exists "forms-portal-workflow_statuses" (
  id bigint generated by default as identity primary key,
  workflow_key varchar(64) not null unique,
  display_name varchar(120) not null,
  clickup_status varchar(120) not null,
  updated_at timestamptz not null default now(),
    constraint forms_portal_workflow_key_check
    check (workflow_key in (
      'requestorFormSubmission', 'tlReviewAndApproval', 'financeValidation',
      'financeProcessing', 'paymentPreparation', 'managementApproval',
      'paymentRelease', 'paymentDocumentation', 'recordsFiling',
      'revisionRequested'
    ))
);

insert into "forms-portal-workflow_statuses"
  (workflow_key, display_name, clickup_status)
values
  ('requestorFormSubmission', 'Requestor Form Submission', 'Requestor Form Submission'),
  ('tlReviewAndApproval', 'TL Review and Approval', 'TL Review and Approval'),
  ('financeValidation', 'Finance Validation', 'Finance Validation'),
  ('financeProcessing', 'Finance Processing', 'Finance Processing'),
  ('paymentPreparation', 'Payment Preparation', 'Payment Preparation'),
  ('managementApproval', 'CFO/CEO Review and Sign-off', 'CFO/CEO Review and Sign-off'),
  ('paymentRelease', 'Payment Release', 'Payment Release'),
  ('paymentDocumentation', 'Payment Documentation', 'Payment Documentation'),
  ('recordsFiling', 'Records Filing', 'Records Filing'),
  ('revisionRequested', 'Revision Requested', 'Revision Requested')
on conflict (workflow_key) do update set
  display_name = excluded.display_name,
  clickup_status = excluded.clickup_status,
  updated_at = now();

create table if not exists "forms-portal-rfp_sequence" (
  id bigint generated by default as identity primary key,
  reference_month varchar(6) not null,
  sequence_number integer not null unique,
  base_reference varchar(32) not null unique,
  submission_path varchar(16) not null default 'option-a',
  entity_code varchar(16) not null default '',
  payee_token varchar(160) not null default '',
  revision_count integer not null default 0,
  clickup_task_id varchar(64),
  created_at timestamptz not null default now(),
  constraint forms_portal_rfp_sequence_number_check check (sequence_number between 1 and 9999),
  constraint forms_portal_rfp_sequence_path_check check (submission_path = 'option-a')
);

create sequence if not exists forms_portal_rfp_sequence_number_seq start 1 maxvalue 9999 no cycle;

select setval(
  'forms_portal_rfp_sequence_number_seq',
  case when coalesce((select max(sequence_number) from "forms-portal-rfp_sequence"), 0) = 0 then 1
       else (select max(sequence_number) from "forms-portal-rfp_sequence") end,
  case when coalesce((select max(sequence_number) from "forms-portal-rfp_sequence"), 0) > 0 then true else false end
);

create or replace function forms_portal_allocate_rfp_sequence(
  p_reference_month varchar(6),
  p_entity_code varchar(16),
  p_payee_token varchar(160)
) returns table (base_reference varchar(32), sequence_number integer)
language plpgsql security definer as $$
declare next_number integer;
begin
  select nextval('forms_portal_rfp_sequence_number_seq')::integer into next_number;
  if next_number > 9999 then raise exception 'RFP sequence limit reached'; end if;
  insert into "forms-portal-rfp_sequence" (reference_month, sequence_number, base_reference, entity_code, payee_token)
  values (p_reference_month, next_number, 'RFP-' || p_reference_month || '-' || lpad(next_number::text, 4, '0'), p_entity_code, p_payee_token);
  return query select 'RFP-' || p_reference_month || '-' || lpad(next_number::text, 4, '0'), next_number;
end; $$;

insert into "forms-portal-RBAC"
  (user_id, name, email, department, role, status)
values
  ('usr-1', 'Dave Policarpio', 'dave@primephilippines.com', 'Executive', 'admin', 'active'),
  ('usr-2', 'Finance Officer', 'finance@primephilippines.com', 'Finance & Accounting', 'finance', 'active'),
  ('usr-3', 'Department Team Leader', 'tl.lead@primephilippines.com', 'ISD', 'approver', 'active'),
  ('usr-4', 'Operations Staff', 'staff@primephilippines.com', 'Operations', 'requestor', 'active')
on conflict (user_id) do update set
  name = excluded.name,
  email = excluded.email,
  department = excluded.department,
  role = excluded.role,
  status = excluded.status,
  updated_at = now();
