-- Forms Portal database schema.
-- Hyphens require quoted PostgreSQL identifiers; these names intentionally
-- follow the requested forms-portal-(table-name) convention.

create table if not exists "forms-portal-form_destinations" (
  id bigint generated by default as identity primary key,
  form_type varchar(32) not null unique,
  display_name varchar(120) not null,
  clickup_workspace_id varchar(64) not null default '',
  clickup_list_id varchar(64) not null default '',
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint forms_portal_form_destinations_type_check
    check (form_type in ('rfp', 'gw-rfp', 'travel-budget'))
);

create index if not exists forms_portal_form_destinations_enabled_idx
  on "forms-portal-form_destinations" (enabled);

delete from "forms-portal-form_destinations"
where form_type not in ('rfp', 'gw-rfp', 'travel-budget');

alter table "forms-portal-form_destinations"
  drop constraint if exists forms_portal_form_destinations_type_check;
alter table "forms-portal-form_destinations"
  add constraint forms_portal_form_destinations_type_check
  check (form_type in ('rfp', 'gw-rfp', 'travel-budget'));

insert into "forms-portal-form_destinations"
  (form_type, display_name, clickup_workspace_id, clickup_list_id, enabled)
values
  ('rfp', 'PRIME RFP submissions', '9014981136', '901420772915', true),
  ('gw-rfp', 'GW RFP submissions', '9014981136', '901420772915', true),
  ('travel-budget', 'Travel Budget requests', '9014981136', '901420772915', true)
on conflict (form_type) do update set
  display_name = excluded.display_name,
  clickup_workspace_id = excluded.clickup_workspace_id,
  clickup_list_id = excluded.clickup_list_id,
  enabled = excluded.enabled,
  updated_at = now();

create table if not exists "forms-portal-RBAC" (
  id bigint generated by default as identity primary key,
  user_id varchar(120) not null unique,
  name varchar(160) not null,
  email varchar(255) not null unique,
  department varchar(160) not null default 'Operations',
  role varchar(32) not null,
  status varchar(16) not null default 'active',
  clickup_task_id varchar(120),
  permissions jsonb,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  constraint forms_portal_rbac_role_check
    check (role in ('admin', 'approver', 'finance', 'requestor')),
  constraint forms_portal_rbac_status_check
    check (status in ('active', 'inactive'))
);

create index if not exists forms_portal_rbac_department_idx
  on "forms-portal-RBAC" (department);

create index if not exists forms_portal_rbac_status_idx
  on "forms-portal-RBAC" (status);

alter table "forms-portal-RBAC"
  add column if not exists clickup_task_id varchar(120);

alter table "forms-portal-RBAC"
  add column if not exists permissions jsonb;

create table if not exists "forms-portal-workflow_statuses" (
  id bigint generated by default as identity primary key,
  workflow_key varchar(64) not null unique,
  display_name varchar(120) not null,
  clickup_status varchar(120) not null,
  updated_at timestamptz not null default now(),
    constraint forms_portal_workflow_key_check
    check (workflow_key in (
      'requestorFormSubmission', 'tlReviewAndApproval', 'financeValidation',
      'financeProcessing', 'paymentPreparation', 'managementApproval',
      'paymentRelease', 'paymentDocumentation', 'recordsFiling',
      'revisionRequested'
    ))
);

-- Replace the constraint when upgrading an existing installation. CREATE TABLE
-- IF NOT EXISTS does not modify constraints that were created by an older schema.
delete from "forms-portal-workflow_statuses"
where workflow_key not in (
  'requestorFormSubmission', 'tlReviewAndApproval', 'financeValidation',
  'financeProcessing', 'paymentPreparation', 'managementApproval',
  'paymentRelease', 'paymentDocumentation', 'recordsFiling', 'revisionRequested'
);

alter table "forms-portal-workflow_statuses"
  drop constraint if exists forms_portal_workflow_key_check;
alter table "forms-portal-workflow_statuses"
  add constraint forms_portal_workflow_key_check
  check (workflow_key in (
    'requestorFormSubmission', 'tlReviewAndApproval', 'financeValidation',
    'financeProcessing', 'paymentPreparation', 'managementApproval',
    'paymentRelease', 'paymentDocumentation', 'recordsFiling', 'revisionRequested'
  ));

insert into "forms-portal-workflow_statuses"
  (workflow_key, display_name, clickup_status)
values
  ('requestorFormSubmission', 'REQUESTOR FORM SUBMISSION', 'REQUESTOR FORM SUBMISSION'),
  ('tlReviewAndApproval', 'TL REVIEW AND APPROVAL', 'TL REVIEW AND APPROVAL'),
  ('financeValidation', 'FINANCE VALIDATION', 'FINANCE VALIDATION'),
  ('financeProcessing', 'FINANCE PROCESSING', 'FINANCE PROCESSING'),
  ('paymentPreparation', 'PAYMENT PREPARATION', 'PAYMENT PREPARATION'),
  ('managementApproval', 'CFO/CEO SIGN-OFF', 'CFO/CEO SIGN-OFF'),
  ('paymentRelease', 'PAYMENT RELEASE', 'PAYMENT RELEASE'),
  ('paymentDocumentation', 'PAYMENT DOCUMENTATION', 'PAYMENT DOCUMENTATION'),
  ('recordsFiling', 'RECORDS FILING', 'RECORDS FILING'),
  ('revisionRequested', 'REVISION REQUESTED', 'REVISION REQUESTED')
on conflict (workflow_key) do update set
  display_name = excluded.display_name,
  clickup_status = excluded.clickup_status,
  updated_at = now();

create table if not exists "forms-portal-settings" (
  setting_key varchar(80) primary key,
  setting_value jsonb not null,
  updated_at timestamptz not null default now()
);

insert into "forms-portal-settings" (setting_key, setting_value)
values ('rfpAutofillEnabled', 'true'::jsonb)
on conflict (setting_key) do nothing;

update "forms-portal-workflow_statuses" set display_name = 'REQUESTOR FORM SUBMISSION', clickup_status = 'REQUESTOR FORM SUBMISSION' where workflow_key = 'requestorFormSubmission';
update "forms-portal-workflow_statuses" set display_name = 'TL REVIEW AND APPROVAL', clickup_status = 'TL REVIEW AND APPROVAL' where workflow_key = 'tlReviewAndApproval';
update "forms-portal-workflow_statuses" set display_name = 'FINANCE VALIDATION', clickup_status = 'FINANCE VALIDATION' where workflow_key = 'financeValidation';
update "forms-portal-workflow_statuses" set display_name = 'FINANCE PROCESSING', clickup_status = 'FINANCE PROCESSING' where workflow_key = 'financeProcessing';
update "forms-portal-workflow_statuses" set display_name = 'PAYMENT PREPARATION', clickup_status = 'PAYMENT PREPARATION' where workflow_key = 'paymentPreparation';
update "forms-portal-workflow_statuses" set display_name = 'CFO/CEO SIGN-OFF', clickup_status = 'CFO/CEO SIGN-OFF' where workflow_key = 'managementApproval';
update "forms-portal-workflow_statuses" set display_name = 'PAYMENT RELEASE', clickup_status = 'PAYMENT RELEASE' where workflow_key = 'paymentRelease';
update "forms-portal-workflow_statuses" set display_name = 'PAYMENT DOCUMENTATION', clickup_status = 'PAYMENT DOCUMENTATION' where workflow_key = 'paymentDocumentation';
update "forms-portal-workflow_statuses" set display_name = 'RECORDS FILING', clickup_status = 'RECORDS FILING' where workflow_key = 'recordsFiling';
update "forms-portal-workflow_statuses" set display_name = 'REVISION REQUESTED', clickup_status = 'REVISION REQUESTED' where workflow_key = 'revisionRequested';

insert into "forms-portal-RBAC"
  (user_id, name, email, department, role, status)
values
  ('usr-1', 'Dave Policarpio', 'dave@primephilippines.com', 'Executive', 'admin', 'active'),
  ('usr-2', 'Finance Officer', 'finance@primephilippines.com', 'Finance & Accounting', 'finance', 'active'),
  ('usr-3', 'Department Team Leader', 'tl.lead@primephilippines.com', 'ISD', 'approver', 'active'),
  ('usr-4', 'Operations Staff', 'staff@primephilippines.com', 'Operations', 'requestor', 'active')
on conflict (user_id) do update set
  name = excluded.name,
  email = excluded.email,
  department = excluded.department,
  role = excluded.role,
  status = excluded.status,
  updated_at = now();
