-- Form destination configuration for the Forms Portal.
-- The current app stores these values in src/lib/featureFlags.json; this script
-- provides the database schema and seed data for SQL-backed persistence.

create table if not exists form_destinations (
  id bigint generated by default as identity primary key,
  form_type varchar(32) not null unique,
  display_name varchar(120) not null,
  clickup_workspace_id varchar(64) not null default '',
  clickup_list_id varchar(64) not null default '',
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint form_destinations_form_type_check
    check (form_type in ('rfp', 'gw-rfp', 'travel-budget', 'po', 'pcv'))
);

create index if not exists form_destinations_enabled_idx
  on form_destinations (enabled);

insert into form_destinations
  (form_type, display_name, clickup_workspace_id, clickup_list_id, enabled)
values
  ('rfp', 'PRIME RFP submissions', '9014981136', '901420772915', true),
  ('gw-rfp', 'GW RFP submissions', '9014981136', '901420772915', true),
  ('travel-budget', 'Travel Budget requests', '9014981136', '901420772915', true),
  ('po', 'Purchase Order requests', '9014981136', '', true),
  ('pcv', 'Petty Cash Voucher requests', '9014981136', '', true)
on conflict (form_type) do update set
  display_name = excluded.display_name,
  clickup_workspace_id = excluded.clickup_workspace_id,
  clickup_list_id = excluded.clickup_list_id,
  enabled = excluded.enabled,
  updated_at = now();
