-- Apply this migration in Supabase SQL Editor for an existing deployment.
-- It installs the Finance sequence table and RPC used by /api/rfp/submit.

create table if not exists public."forms-portal-rfp_sequence" (
  id bigint generated by default as identity primary key,
  reference_month varchar(6) not null,
  sequence_number integer not null unique,
  base_reference varchar(32) not null unique,
  submission_path varchar(16) not null default 'option-a',
  entity_code varchar(16) not null default '',
  payee_token varchar(160) not null default '',
  revision_count integer not null default 0,
  clickup_task_id varchar(64),
  created_at timestamptz not null default now(),
  constraint forms_portal_rfp_sequence_number_check check (sequence_number between 1 and 9999),
  constraint forms_portal_rfp_sequence_path_check check (submission_path = 'option-a')
);

create sequence if not exists public.forms_portal_rfp_sequence_number_seq start 1 maxvalue 9999 no cycle;

do $$
declare current_max integer;
begin
  select coalesce(max(sequence_number), 0) into current_max from public."forms-portal-rfp_sequence";
  if current_max > 0 then
    perform setval('public.forms_portal_rfp_sequence_number_seq', current_max, true);
  end if;
end $$;

create or replace function public.forms_portal_allocate_rfp_sequence(
  p_reference_month varchar(6),
  p_entity_code varchar(16),
  p_payee_token varchar(160)
) returns table (base_reference varchar(32), sequence_number integer)
language plpgsql security definer set search_path = public as $$
declare next_number integer;
begin
  select nextval('public.forms_portal_rfp_sequence_number_seq')::integer into next_number;
  if next_number > 9999 then raise exception 'RFP sequence limit reached'; end if;
  insert into public."forms-portal-rfp_sequence" (reference_month, sequence_number, base_reference, entity_code, payee_token)
  values (p_reference_month, next_number, 'RFP-' || p_reference_month || '-' || lpad(next_number::text, 4, '0'), p_entity_code, p_payee_token);
  return query select 'RFP-' || p_reference_month || '-' || lpad(next_number::text, 4, '0'), next_number;
end; $$;

grant execute on function public.forms_portal_allocate_rfp_sequence(varchar, varchar, varchar) to service_role;
